export const synthActions = {
  CREATE_MANAGER: "CREATE_MANAGER",
  CREATE_MASTER_VOLUME: "CREATE_MASTER_VOLUME",
  CREATE_OSCILLATOR: "CREATE_OSCILLATOR",
  DELETE_OSCILLATOR: "DELETE_OSCILLATOR",
  SET_MASTER_VOLUME: "SET_MASTER_VOLUME",
  PLAY: "PLAY",
  SET_WAVE_FORM: "SET_WAVE_FORM",
  STOP: "STOP",
};
